version: '3'

services:

    mongo:
        image: mongo:latest
        ports:
            - 27017:27017
        volumes:
            - ~/git/it-web/docker/mongo/data:/data/db

    it-web:
        build: .
        environment:
            - MONGO_URL=mongodb://mongo/itdb
        ports:
            - 3000:3000
        volumes:
            - .:/usr/local/it-web
            - /usr/local/it-web/node_modules
            - /usr/local/it-web/public/js/node_modules
        command:
            npm run dev
        depends_on:
            - mongo
